sudo: required
services:
    - docker

before_install:
    - docker build -t emanuel/docker-react -f Dockerfile.dev .

script:
    - docker run emanuel/docker-react npm run test -- --coverage --watchAll=false