sudo: required
services:
    - docker

before_install:
    - docker build -t emanuel/docker-react -f Dockerfile.dev .

script:
    - docker run emanuel/docker-react npm run test -- --coverage --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "My Docker App"
    env: "MyDockerApp-env"
    bucket_name: "elasticbeanstalk-eu-north-1-893654888946"
    bucket_path: "My Docker App"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"